/**
 * GENERATED by `scripts/mirror_web_legal_constants.py`, via `scripts/sync_web_legal.py`.
 * Do not edit.
 *
 * The website publishes the application's legal documents, and these are how it checks that the
 * copy it publishes is the one that was written: a test here hashes this repository's own
 * `components/Legal/*.tsx` and compares. A copy that has drifted fails in THIS repository's CI,
 * without needing to read the application's tree — which it will not be able to do once the two are
 * separate repositories.
 *
 * The numbers are COPIED from the application, never recomputed from the files beside them. A
 * digest computed here would be a checksum of this repository's own content, which agrees with
 * every possible text and pins nothing.
 *
 * WHAT THIS CANNOT PROVE is that the DEPLOYED site serves the current version. Nothing in CI can,
 * without reaching the network. That is residual, and handled by publishing rather than by a test.
 */

/** The version registration records as accepted, and the date both documents print. */
export const TERMS_VERSION = "2026-09-20";
export const TERMS_DISPLAY_DATE = "20 September 2026";

/**
 * SHA-256 of each document's `SECTIONS` array: everything from `const SECTIONS: Section[] = [` up
 * to the `Sub-components` banner, with carriage returns removed.
 *
 * THE SCOPE IS NOT A DETAIL. The two copies legitimately differ OUTSIDE that range — this one
 * carries a "this is a copy" header, and a breadcrumb pointing at the site root rather than at the
 * application's Settings screen, which does not exist here. A digest over the whole file would
 * differ between the two by construction and could never agree.
 *
 * Carriage returns are stripped because two checkouts can disagree about line endings while the
 * words do not.
 */
export const PRIVACY_SECTIONS_SHA256 = "05544267f17d45f6a1adb12030945a2cae29df197c91329f076969ea93fa8f31";
export const TERMS_SECTIONS_SHA256 = "e3e369f766aaaae0dff63f0c2b4c18d49d669b1b729402430d52a63e72304ce2";
