/**
 * GENERATED by `scripts/sync-from-app.mjs`. Do not edit.
 *
 * The numbers are COPIED from the application's `desktop/src/shared/legal.ts`, never recomputed
 * from the files beside them: a digest computed here would be a checksum of this repository's own
 * content, which agrees with every possible text and pins nothing.
 *
 * `src/lib/__checks__` — that is, `scripts/check-legal-digest.mjs` — hashes this repository's
 * `components/Legal/*.tsx` and compares. It runs as `prebuild`, so a deploy fails rather than
 * publishing a legal document that is not the one the application records consent against.
 */

/** The version registration records as accepted, and the date both documents print. */
export const TERMS_VERSION = "2026-09-20";
export const TERMS_DISPLAY_DATE = "20 September 2026";

/**
 * SHA-256 of each document's `SECTIONS` array: everything from `const SECTIONS: Section[] = [` up
 * to the `Sub-components` banner, with carriage returns removed.
 *
 * THE SCOPE IS NOT A DETAIL. The two copies legitimately differ outside that range — this one
 * carries the header above and a breadcrumb pointing at this site's root. A digest over the whole
 * file would differ between them by construction and could never agree.
 */
export const PRIVACY_SECTIONS_SHA256 = "05544267f17d45f6a1adb12030945a2cae29df197c91329f076969ea93fa8f31";
export const TERMS_SECTIONS_SHA256 = "e3e369f766aaaae0dff63f0c2b4c18d49d669b1b729402430d52a63e72304ce2";
