"use client";

/**
 * ── A COPY, AND THE COPY IS THE POINT ─────────────────────────────────────────────────────────────
 *
 * This file is `desktop/renderer/src/components/Legal/PrivacyClient.tsx` with one change: the breadcrumb
 * points at the site root rather than at the application's Settings screen, which does not exist
 * here. `tests/test_marketing_pages.py` compares the two files' SECTIONS blocks and their
 * "Last updated" dates, and fails on any difference.
 *
 * WHY IT IS DUPLICATED AT ALL. Both places must publish it. The desktop app shows it in its
 * sign-up dialog, where a person accepts it — so it has to ship inside the binary and work offline.
 * Stripe and the app stores need a public URL, and a reader deciding whether to install anything
 * wants to read the terms first — so it has to be a web page. Neither can import from the other:
 * they are separate packages with separate tsconfig roots and separate build pipelines.
 *
 * WHAT IT REPLACED, because it is worth knowing how far this had drifted. The version here was
 * dated 1 January 2025 and described OAuth sign-in with Microsoft and Google, cookies for session
 * and CSRF tokens, analytics retained 90 days, and staff reviewing conversations for quality
 * assurance — none of which existed. The application's copy was rewritten twice since: once to
 * describe a local-first app, and again when the optional account arrived. This website was still
 * serving the 2025 text to the public, which is the copy Stripe and a prospective user would read.
 *
 * DO NOT EDIT THIS FILE. Edit the application's, then copy it here; the test names the command.
 */

import { useState } from "react";
import Link from "next/link";

// ── Types ──────────────────────────────────────────────────────────────────

interface Section {
  id: string;
  title: string;
  content: React.ReactNode;
}

/**
 * ── WHY THIS DOCUMENT WAS REWRITTEN ───────────────────────────────────────────────────────────
 *
 * It was a hosted-platform privacy policy, and this is a local-first desktop application. Almost
 * every operative sentence described a system that does not exist: OAuth sign-in with Microsoft and
 * Google, cookies for session and CSRF tokens, IP addresses and geolocation, analytics retained 90
 * days, authentication logs retained 12 months, profile data deleted "within 90 days" of account
 * deletion, staff reviewing conversations for quality assurance, disclosure to cloud hosting
 * vendors, and TLS 1.2+ / AES-256 / MFA protecting a server nobody runs.
 *
 * A privacy policy that overstates collection is not a harmless placeholder — it is a factual
 * misstatement about the one document a user consults precisely because they cannot read the source.
 *
 * ── AND WHY IT CHANGED AGAIN, WHEN THE OPTIONAL ACCOUNT ARRIVED ──────────────────────────────────
 *
 * The rewrite said "no account to create, no sign-in, and no VoidCode server" while the Models page
 * already shipped a sign-in form for the hosted model. So the error flipped direction: it now
 * UNDERSTATED what happens, which is the unsafe way round. The document is organised around the one
 * distinction that is actually true — without an account nothing reaches us; with one, section 6
 * lists what our server keeps — and every server-side claim there was checked against `apps/api`:
 *
 *   - account columns ...................... `models/user.py`, `models/auth_token.py` (token HASH,
 *                                            expiry, no IP or device)
 *   - credits, ledger, metering records .... `models/gpu_billing.py`, `models/credit_voucher.py`
 *   - conversations not stored or logged ... no table holds them; `tests/test_prompts_are_not_logged.py`
 *                                            (two log lines kept 60 characters of each question
 *                                            until this rewrite found them)
 *   - hashed attempt counters, ≤ 1 hour .... `ratelimit.py`
 *   - one kind of email, via Resend ........ `services/email_service.py`, `routers/auth.py`
 *   - card details never reach us .......... `services/payments.py` (hosted Stripe Checkout)
 *   - no account deletion endpoint ......... hence "email the Privacy Officer", not a button
 *   - no log retention period .............. none is configured, so none is claimed
 *
 * Note the direction of the error. Every claim removed here described *more* data handling than
 * happens, which is the safer direction to be wrong in but still wrong. Section 2 already carried a
 * comment recording that student IDs and LMS enrolment records had been struck for exactly this
 * reason; that correction was right and did not go far enough.
 *
 * EVERY FACTUAL CLAIM BELOW WAS CHECKED AGAINST THE CODE, and each is followed here by where:
 *
 *   - signed out, nothing reaches us ....... `src/main/account/session.ts`, `platform/http.ts`
 *   - account details held in memory only . `src/main/account/session.ts` (no `store/` import)
 *   - the profile columns .................. the `profile` table in `src/main/store/db.ts`, which
 *                                            deliberately has no email column
 *   - one local SQLite file ................ `src/main/store/db.ts`
 *   - no cookies; localStorage for layout .. `lib/shell/usePanels.tsx`; the UI loads over `app://`
 *   - hardware readings stay local ......... `lib/shell/useTelemetry.ts`, `hardware/scan.ts`
 *   - what can leave the machine ........... `inference/registry.ts` (OpenRouter, key-gated) and
 *                                            `net/allowlist.ts` (the agent's fetch allowlist)
 *   - submissions run locally .............. `exec/sandbox.ts` (Pyodide, no network)
 *   - the API key's storage ................ `inference/vault.ts`, `store/secrets.ts`
 *
 * WHAT WAS DELIBERATELY NOT CHANGED, because it is a legal or commercial decision rather than a
 * description of software: the legal entity and its contact details, the postal address, the
 * Privacy Officer email, the jurisdiction, and the statutory compliance claims in the badge row.
 * Those need a human who can decide them. The rewrite is confined to what the software does.
 */

// ── Sections ───────────────────────────────────────────────────────────────

const SECTIONS: Section[] = [
  {
    id: "overview",
    title: "1. Overview",
    content: (
      <>
        <p>
          VoidCode AI ("VoidCode", "we", "our", or "us") publishes the VoidCode application. This
          Privacy Policy explains what the application stores, where it stores it, when anything
          leaves your computer, and what we hold if you choose to create an account.
        </p>
        <p>
          <strong className="text-ink-2">
            An account is optional, and without one the application runs entirely on your machine.
          </strong>{" "}
          The editor, the grader, local models and your profile all work without signing in, and a
          signed-out application sends nothing to a VoidCode server. We do not receive your profile,
          your code, your submissions, or your local conversations — not because we choose to discard
          them, but because nothing sends them to us.
        </p>
        <p>
          An account exists for one purpose: using the VoidCode model, which runs on our servers and
          is paid for with credits. If you create one, we hold the account details described in
          section 6, and conversations you send to the VoidCode model pass through our servers to be
          answered. Section 3 lists every way anything leaves your computer, with or without an
          account.
        </p>
        <p>
          Most of this Policy therefore describes data <em>you</em> hold rather than data we hold,
          and several rights that a hosted service would grant you are instead things you can simply
          do yourself. Where that is the case, it says so.
        </p>
        <p>
          Read it alongside our{" "}
          <Link href="/terms" className="text-ink hover:text-ink underline underline-offset-2 transition-colors">
            Terms of Use
          </Link>
          .
        </p>
        <p>
          VoidCode complies with the <em>Privacy Act 1988</em> (Cth), the Australian Privacy
          Principles (APPs), and applicable Victorian privacy legislation.
        </p>
      </>
    ),
  },
  {
    id: "information-collected",
    title: "2. What Is Stored on Your Computer",
    content: (
      <>
        <p>
          Everything the application records about your work is kept in a single database file named{" "}
          <code className="text-ink-2">voidcode.db</code>, inside the application-data folder your
          operating system allocates to VoidCode. It is an ordinary file on your disk. You can copy
          it, back it up, inspect it, or delete it.
        </p>

        <h3 className="text-ink text-[13px] font-medium mt-4 mb-2">2.1 Details you enter</h3>
        <ul>
          <li>
            A local profile, entirely optional: display name, biography, date of birth, country,
            occupation, profile photo, and time zone
          </li>
          <li>Your code submissions, drafts, and which exercises you have solved</li>
          <li>Your conversations with the tutor and with the coding assistant</li>
          <li>Notifications the application has generated for you</li>
        </ul>
        <p>
          <strong className="text-ink-2">The local profile has no email address field</strong>, and no
          password. The database has no column for either. Your local profile is not your VoidCode
          account, is not sent to us, and is not linked to an account if you create one.
        </p>

        <h3 className="text-ink text-[13px] font-medium mt-4 mb-2">2.2 Recorded as you work</h3>
        <ul>
          <li>Which projects you have opened in Build mode, so the File menu can list them</li>
          <li>Window positions and panel layout, so the application reopens as you left it</li>
          <li>
            A record of what the coding assistant did — files it read, changes it proposed — kept so
            that "what did it do to my repository" stays answerable after the window closes
          </li>
        </ul>
        <p>
          The CPU, memory and GPU figures in the status bar are read from your machine to be
          displayed and are never stored or transmitted.
        </p>

        <h3 className="text-ink text-[13px] font-medium mt-4 mb-2">2.3 Cookies and browser storage</h3>
        <p>
          <strong className="text-ink-2">The application sets no cookies.</strong> Its interface is
          not served over the web, so there is no session cookie, no tracking cookie, and no CSRF
          token. Browser local storage holds one thing: which panels you have open and how you have
          sized them.
        </p>

        <h3 className="text-ink text-[13px] font-medium mt-4 mb-2">2.4 If you sign in</h3>
        <p>
          Signing in gives the application a session token. It is encrypted with your operating
          system&apos;s credential store, like the API key in section 5, and is never shown to you or
          readable by the interface. Your account&apos;s email address and name are fetched from us
          while the application is open and held in memory only — they are not written to the local
          database. Signing out removes the token.
        </p>
      </>
    ),
  },
  {
    id: "what-leaves",
    title: "3. What Leaves Your Computer",
    content: (
      <>
        <p>
          By default, nothing. Models run through a local Ollama or llama.cpp on your own machine,
          and your code is executed inside the application in a WebAssembly sandbox that has no
          network access at all. Anything reaching the internet happens in one of these ways, and
          every one of them requires you to act first:
        </p>
        <ul>
          <li>
            <strong className="text-ink-2">A remote model, if you add a key.</strong> Providing an
            OpenRouter key and selecting one of its models sends that conversation — your prompt, and
            any code or images attached to it — to OpenRouter, under their privacy policy. With no
            key, their models are listed and cannot be used. It goes to them, not to us.
          </li>
          <li>
            <strong className="text-ink-2">Your VoidCode account, if you create one.</strong> Creating
            an account, signing in, resetting a password, checking your credit balance and buying
            credits all send what that step needs to us — for example your email address and password
            when you sign in. If you sign in with Google or Microsoft instead, the application opens
            your browser at their sign-in page and receives the result; section 6.4 sets out that
            exchange. While you are signed in, the application also checks with us that your sign-in
            is still valid and fetches your balance and the list of VoidCode models. Section 6
            describes what we keep.
          </li>
          <li>
            <strong className="text-ink-2">The research library, when you open it.</strong> The
            Research page asks our servers for the list of papers and for the breakdowns of the one
            you open. This works without an account and sends nothing about you: the request carries
            a paper’s name and, if you are signed in, your session — so that the sections you have
            already read can be ticked. Marking a section read needs an account, because there is
            nowhere else to keep it. Nothing is fetched until you open that page, and the PDF itself
            is opened in your own browser, which contacts arXiv rather than us.
          </li>
          <li>
            <strong className="text-ink-2">The VoidCode model, if you select it.</strong> This one
            goes <em>to us</em>. Choosing the &ldquo;VoidCode&rdquo; provider sends that conversation —
            your prompt, and any code or images attached to it — to our servers, where a model we run
            answers it. We do this because the model is far larger than anything most machines can
            hold, and running it costs us GPU time, which is why it needs an account and is metered
            against credits rather than free. It is never selected for you, and the local providers
            keep working without it.
          </li>
          <li>
            <strong className="text-ink-2">Downloading a model.</strong> Ollama fetches the weights
            from its own registry. The request is made by Ollama on your machine, and carries nothing
            about you beyond which model you asked for.
          </li>
          <li>
            <strong className="text-ink-2">The assistant reading documentation.</strong> When you ask
            it to look something up, it may fetch a page from a fixed list of documentation and
            package-registry sites — Python, MDN, npm, PyPI, crates.io, GitHub and similar. It cannot
            reach any other host, and it cannot reach anything on your local network.
          </li>
        </ul>
        <p>
          Your submissions, your progress, your local profile and your local conversations are not
          part of any of that. The application collects no usage analytics, crash reports,
          performance metrics or device identifiers, because it contains nothing that would send
          them. When it does contact our servers, those servers see the IP address the request came
          from, as any server does — section 6 says what is kept.
        </p>
      </>
    ),
  },
  {
    id: "ai-data",
    title: "4. The Tutor and the Coding Assistant",
    content: (
      <>
        <p>
          Your conversations are rows in the local database described in section 2. They are used to
          give the model the earlier turns of the same conversation, and to let you reopen a
          conversation later.
        </p>
        <ul>
          <li>
            <strong className="text-ink-2">Nobody reviews them.</strong> A conversation with a local
            model never reaches us. A conversation sent to the VoidCode model passes through our
            servers to be answered, and is not stored there: our servers do not write its text to
            their database or to their logs. There is no quality-assurance review and no safety
            monitoring of what you write.
          </li>
          <li>
            <strong className="text-ink-2">Nothing is used to train a model.</strong> No aggregate
            analysis, no learning-pattern research, no model improvement from your data.
          </li>
        </ul>
        <div className="mt-4 flex items-start gap-3 rounded-xl border border-line-strong bg-void-2 px-4 py-3">
          <svg className="mt-0.5 h-4 w-4 flex-shrink-0 text-ink-2" viewBox="0 0 20 20" fill="currentColor">
            <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
          </svg>
          <p className="text-[12px] leading-relaxed text-ink-2">
            If you have selected a remote model — OpenRouter or the VoidCode model — treat what you type
            as leaving your machine. Avoid putting passwords, financial details or health information in
            a conversation you are sending to a provider.
          </p>
        </div>
      </>
    ),
  },
  {
    id: "api-keys",
    title: "5. Your API Key",
    content: (
      <>
        <p>
          If you add an OpenRouter key, it is encrypted using your operating system&apos;s credential
          store — DPAPI on Windows, Keychain on macOS, or your keyring on Linux — and the encrypted
          result is kept in the same local database. What decrypts it stays with the operating system,
          so the database file on its own does not yield the key.
        </p>
        <ul>
          <li>
            The key is never displayed back to you, and no part of the interface is able to read it.
            It is attached to a request at the moment the request is made and held nowhere else.
          </li>
          <li>
            You can remove it at any time from the model manager, which deletes it from the database.
          </li>
          <li>
            If your system offers no keyring the application can rely on, the key is held only for
            the current session and never written to disk. The model manager tells you which of the
            two happened when you save it. The same applies to a VoidCode sign-in, and the Account
            page says so when it happens.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "account",
    title: "6. If You Create an Account",
    content: (
      <>
        <p>
          Everything in this section applies only if you create a VoidCode account. Without one, we
          hold none of it.
        </p>

        <h3 className="text-ink text-[13px] font-medium mt-4 mb-2">6.1 What we keep</h3>
        <ul>
          <li>Your email address and the name you gave</li>
          <li>
            Your password as an Argon2id hash — a one-way transformation, so we cannot read the
            password back
          </li>
          <li>
            When the account was created, when you last signed in, when your password last changed,
            and when your email address was confirmed by a code we sent it
          </li>
          <li>Which version of these documents you accepted, and when</li>
          <li>
            For each device you sign in on, a hash of its session token and when that session expires
            — not the token itself, and not the device&apos;s name, model or IP address
          </li>
          <li>A welcome message created with the account</li>
          <li>
            Your credit balance, and a ledger of credits added, held and spent. When the VoidCode model
            is metered, each answer also leaves a record of how long it took, what it cost, and which
            of our servers answered it — but not what you asked or what it said
          </li>
          <li>Which voucher codes you redeemed</li>
          <li>
            Which sections of which research papers you have opened, and when you first finished
            all four of a paper. Not how long you spent, and not what you thought of it — the page
            says outright that this counts sections opened rather than sections understood
          </li>
          <li>
            If you connect a Google or Microsoft account: which provider it is, the identifier that
            provider uses for your account, the email address it gave us and whether it confirmed
            that address, when it was connected and when it was last used to sign in. For a
            Microsoft work or school account, the identifier of the organisation it belongs to
          </li>
        </ul>

        <h3 className="text-ink text-[13px] font-medium mt-4 mb-2">6.2 What our servers record in passing</h3>
        <ul>
          <li>
            <strong className="text-ink-2">Server logs.</strong> Our servers log events such as a
            sign-in that failed, a password that was changed, or a code that was sent, with the email
            address involved, so that misuse of an account can be investigated. Like most web servers,
            they also log the IP address and path of each request they receive.
          </li>
          <li>
            <strong className="text-ink-2">Attempt limits.</strong> To slow down password guessing,
            our servers count recent attempts per IP address and per email address. Both are stored
            only as a keyed hash, and each count lapses after at most an hour.
          </li>
        </ul>

        <h3 className="text-ink text-[13px] font-medium mt-4 mb-2">6.3 What we use it for</h3>
        <p>
          Signing you in, sending you the codes you ask for, running the VoidCode model for you,
          keeping your credit balance, and protecting accounts from misuse. We send an account one
          kind of email — the 6-digit code you request to reset or set a password — and no newsletters
          or marketing.
        </p>

        <h3 className="text-ink text-[13px] font-medium mt-4 mb-2">
          6.4 If you sign in with Google or Microsoft
        </h3>
        <p>
          This is one of the ways to sign in, not a requirement, and an email address with a password
          does the same job. If you use it, here is the whole exchange:
        </p>
        <ul>
          <li>
            <strong className="text-ink-2">You sign in to them, not to us.</strong> The application
            opens your own browser at Google&apos;s or Microsoft&apos;s sign-in page — not a window
            inside the application — so what you type goes to them. We never receive your password
            for that account and cannot.
          </li>
          <li>
            <strong className="text-ink-2">We ask for your name and email address, and nothing
            else.</strong> No access to your mail, files, calendar, contacts or organisation
            directory is requested, which is why the consent screen you see is a short one.
          </li>
          <li>
            <strong className="text-ink-2">We do not ask to keep acting as you.</strong> The
            application asks for a single sign-in and no standing permission, so nothing we hold
            lets us reach your Google or Microsoft account afterwards.
          </li>
          <li>
            <strong className="text-ink-2">They learn that you signed in to VoidCode</strong>, and
            when, because they are the ones confirming it. What they then record is governed by
            their own privacy policy, not this one.
          </li>
          <li>
            <strong className="text-ink-2">We check that they confirmed your address.</strong> An
            address a provider has not confirmed is not used to reach an existing account, because
            an unconfirmed address is not proof that it is yours.
          </li>
        </ul>
        <p>
          You can connect or use either provider from the Account page. What connecting stores is the
          last item in section 6.1 — an identifier and an address, not a credential.
        </p>
      </>
    ),
  },
  {
    id: "disclosure",
    title: "7. Disclosure of Information",
    content: (
      <>
        <p>
          We do not sell, rent or trade your personal information. Without an account the reason is
          structural rather than a promise about our conduct: we do not have it.
        </p>
        <p>
          With an account, a small number of companies handle part of it so the account can work, each
          named in section 11: a payment processor if you buy credits, an email delivery service for
          the codes you request, Google or Microsoft if you choose to sign in with one of them, and
          the providers whose servers our service and the VoidCode model run on.
        </p>
        <ul>
          <li>
            <strong className="text-ink-2">A legal demand to us</strong> can reach only what section 6
            describes, and only for account holders. Your code, submissions, local conversations and
            local profile are not in our possession. A demand directed at you, or at your computer, is
            between you and whoever makes it.
          </li>
          <li>
            <strong className="text-ink-2">A change of ownership</strong> would carry the account
            records in section 6 with it, and nothing else, since nothing else is held. If that ever
            changed, this Policy would have to change first, and section 12 says how you would be told.
          </li>
        </ul>
        <p>
          Where you have chosen to use OpenRouter, it receives what you send it and handles it under
          its own policy. See section 3.
        </p>
      </>
    ),
  },
  {
    id: "data-retention",
    title: "8. Retention and Deletion",
    content: (
      <>
        <p>
          <strong className="text-ink-2">On your computer</strong>, your data stays on your disk until
          you remove it, and you do not need our involvement — or our permission — to do so.
        </p>
        <ul>
          <li>
            <strong className="text-ink-2">Individual items:</strong> delete a conversation in the
            application and its messages are removed from the database. Records of what the coding
            assistant did to your files deliberately outlive the conversation that prompted them, so
            that tidying up a chat does not erase the audit trail of changes to your repository.
          </li>
          <li>
            <strong className="text-ink-2">Everything:</strong> delete the application-data folder
            described in section 2, or uninstall the application. Because we hold no copy of it, we
            also cannot restore any of it for you. If your data matters to you, back up that folder.
          </li>
        </ul>
        <p>
          <strong className="text-ink-2">On our servers</strong>, the account records in section 6 are
          kept while the account exists. A sign-in session lasts 90 days unless you sign out first,
          and a password code expires after 15 minutes; expired and signed-out sessions are marked as
          ended rather than erased. We have not yet set a fixed period for keeping server logs, and
          until we do, this Policy will not claim one.
        </p>
        <p>
          Signing out does not delete an account. The application does not yet have a button that
          does; to delete your account, email the Privacy Officer in section 13 from the email address
          on the account. Deleting it removes the records in section 6.1, except a record that each
          payment was credited, which is kept so the same payment can never be credited twice. Server
          logs written before the deletion are not edited. The payment processor keeps its own record
          of a purchase under its own policy.
        </p>
      </>
    ),
  },
  {
    id: "security",
    title: "9. Security",
    content: (
      <>
        <p>
          Most of the protections that matter are the ones that hold on your own machine, so this
          section starts with those.
        </p>
        <ul>
          <li>
            <strong className="text-ink-2">Your API key and your sign-in</strong> are encrypted with
            the operating system&apos;s credential store, are never shown back to you, and are not
            readable by the interface. See sections 2.4 and 5.
          </li>
          <li>
            <strong className="text-ink-2">Your code runs in a sandbox</strong> — a WebAssembly Python
            runtime with no network access and no access to your filesystem.
          </li>
          <li>
            <strong className="text-ink-2">The coding assistant is confined</strong> to the folder you
            open, cannot escape it via symbolic links, and proposes changes for you to review rather
            than writing them. Applying a batch requires confirming a system dialogue that names every
            file.
          </li>
          <li>
            <strong className="text-ink-2">Its web access is restricted</strong> to the fixed list of
            documentation sites in section 3, and it cannot reach hosts on your local network.
          </li>
        </ul>
        <p>For an account, on our side:</p>
        <ul>
          <li>
            The application sends your password and session to us only over HTTPS. The one other
            address it accepts is a server on your own computer, which never crosses a network.
          </li>
          <li>
            Passwords are stored as Argon2id hashes and sessions as hashes of their tokens, so a copy
            of our database would contain neither.
          </li>
          <li>
            A password code works once, for 15 minutes, and stops working after five wrong guesses.
            Setting a new password with one signs out every other device, and changing your password
            signs out every device but the one you changed it on.
          </li>
        </ul>
        <p>
          Two limits stated plainly rather than left implied. The restriction on which Python modules
          an exercise may import is there to keep exercises honest, and is not a security boundary
          against code written specifically to defeat it. And nothing here protects the database file
          from anyone who already has access to your computer or your user account — it is a normal
          file, and the security of the machine is the security of your data.
        </p>
      </>
    ),
  },
  {
    id: "your-rights",
    title: "10. Your Privacy Rights",
    content: (
      <>
        <p>
          Under the Australian Privacy Principles you have rights over personal information an
          organisation holds about you. For what is on your computer, you can exercise them directly,
          without asking us and without waiting for us:
        </p>
        <ul>
          <li>
            <strong className="text-ink-2">Access</strong> — everything is in the local database
            described in section 2. The application shows it to you, and the file is readable with any
            SQLite tool.
          </li>
          <li>
            <strong className="text-ink-2">Correction</strong> — edit your profile, or any draft or
            conversation, in the application.
          </li>
          <li>
            <strong className="text-ink-2">Deletion</strong> — delete individual items in the
            application, or remove the application-data folder to delete everything. See section 8.
          </li>
          <li>
            <strong className="text-ink-2">Opt-out</strong> — nothing to opt out of. Your data is not
            used for model training or research, and there is no analytics collection to disable. To
            stop data reaching a third party, remove your API key (section 5) or stop using the
            VoidCode model.
          </li>
          <li>
            <strong className="text-ink-2">Complaint</strong> — you may lodge a complaint with the
            Office of the Australian Information Commissioner (OAIC) if you believe your privacy
            rights have been breached.
          </li>
        </ul>
        <p>
          For an account, the Account page shows the details we hold about you, your balance is on the
          Models page, and you can change your password in the application. To obtain a copy of your
          account records, correct something the application cannot, or delete the account, contact our
          Privacy Officer at{" "}
          <a href="mailto:privacy@swin.edu.au" className="text-ink hover:text-ink transition-colors">
            privacy@swin.edu.au
          </a>
          . We will respond within 30 days.
        </p>
      </>
    ),
  },
  {
    id: "third-party",
    title: "11. Third-Party Services",
    content: (
      <>
        <p>
          The application has no third-party integrations that are active by default. There is no
          analytics provider, no error-reporting service and no advertising network. An account can
          be created with an email address and a password alone; Google and Microsoft are offered as
          alternative ways to sign in, and section 6.4 describes exactly what that exchange involves.
        </p>
        <p>
          One party that can become involved is not a third party at all: it is us. Signing in and
          selecting the VoidCode model send information to our servers, as sections 3 and 6 describe.
          We mention it here because a list of &ldquo;who else might see this&rdquo; that quietly omits
          the people who wrote the application would be the least useful kind of accurate.
        </p>
        <p>Other parties can become involved, in every case because you chose it:</p>
        <ul>
          <li>
            <strong className="text-ink-2">OpenRouter</strong> — only once you add a key. Conversations
            you send to one of their models are handled under the{" "}
            <a
              href="https://openrouter.ai/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-ink hover:text-ink transition-colors"
            >
              OpenRouter privacy policy
            </a>
            .
          </li>
          <li>
            <strong className="text-ink-2">Stripe</strong> — only if you buy credits. The purchase is
            completed on Stripe&apos;s own checkout page in your browser, so your card or bank details go
            to Stripe and never to us. Stripe receives an identifier for your account so the payment
            can be credited to it, and handles what you enter under the{" "}
            <a
              href="https://stripe.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-ink hover:text-ink transition-colors"
            >
              Stripe privacy policy
            </a>
            .
          </li>
          <li>
            <strong className="text-ink-2">Resend</strong> — only when you ask for a password code. It
            delivers that email, so it receives your email address and the message.
          </li>
          <li>
            <strong className="text-ink-2">Google or Microsoft</strong> — only if you choose to sign
            in with one of them. They confirm who you are and tell us your name and email address;
            they receive no information about what you do in the application. Google handles this
            under the{" "}
            <a
              href="https://policies.google.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-ink hover:text-ink transition-colors"
            >
              Google privacy policy
            </a>{" "}
            and Microsoft under the{" "}
            <a
              href="https://privacy.microsoft.com/privacystatement"
              target="_blank"
              rel="noopener noreferrer"
              className="text-ink hover:text-ink transition-colors"
            >
              Microsoft privacy statement
            </a>
            .
          </li>
          <li>
            <strong className="text-ink-2">Server and GPU hosting providers</strong> — only for an
            account and the VoidCode model. Our service runs on servers we rent, and the VoidCode model
            on rented GPU servers, so a conversation you send to it passes through them to be answered.
          </li>
          <li>
            <strong className="text-ink-2">The documentation sites in section 3</strong> — reached only
            when you ask the assistant to look something up, and each governed by its own operator.
          </li>
        </ul>
        <p>
          Ollama and llama.cpp are separate programs running on your own machine. They are not
          services we operate, and if you install one, how it behaves is governed by its own project
          rather than by this Policy.
        </p>
        <p>
          We are not responsible for the privacy practices of third parties, and we encourage you to
          review their policies independently.
        </p>
      </>
    ),
  },
  {
    id: "changes",
    title: "12. Changes to This Policy",
    content: (
      <>
        <p>
          We may update this Privacy Policy to reflect changes in the application, or in legal
          requirements. Without an account we hold no contact details for you, and with one we use
          your email address only for the codes described in section 6 —{" "}
          <strong className="text-ink-2">so we do not email you when this Policy changes</strong>.
        </p>
        <p>How you can actually tell:</p>
        <ul>
          <li>
            This page carries a "Last updated" date, revised whenever its substance changes. It ships
            with the application, so the version you are reading is the one that applies to the
            version you have installed.
          </li>
          <li>
            An update that materially changed what the application does with your data would arrive
            with a new release, which you choose to install.
          </li>
        </ul>
        <p>
          If a future version of the application ever collected or transmitted something this Policy
          says it does not, that would be a change to this document and to the release that made it.
        </p>
      </>
    ),
  },
  {
    id: "contact",
    title: "13. Contact & Complaints",
    content: (
      <>
        <p>
          If you have questions, concerns, or wish to exercise your privacy rights, please contact
          our Privacy Officer:
        </p>
        <div className="mt-3 p-4 rounded-lg bg-void-2 border border-line space-y-1">
          <p className="text-ink font-medium">Privacy Officer</p>
          <p>VoidCode AI</p>
          <p>John Street, Hawthorn VIC 3122, Australia</p>
          <p>
            Email:{" "}
            <a href="mailto:privacy@swin.edu.au" className="text-ink hover:text-ink transition-colors">
              privacy@swin.edu.au
            </a>
          </p>
        </div>
        <p className="mt-4">
          If you are not satisfied with our response, you may lodge a complaint with the{" "}
          <a
            href="https://www.oaic.gov.au"
            target="_blank"
            rel="noopener noreferrer"
            className="text-ink hover:text-ink transition-colors"
          >
            Office of the Australian Information Commissioner (OAIC)
          </a>
          .
        </p>
      </>
    ),
  },
];

// ── Sub-components ─────────────────────────────────────────────────────────

function TableOfContents({
  activeId,
  onSelect,
}: {
  activeId: string;
  onSelect: (id: string) => void;
}) {
  return (
    <nav className="sticky top-6 w-64 flex-shrink-0 hidden lg:block">
      <p className="text-[10px] font-semibold uppercase tracking-widest text-ink-3 mb-4">
        Table of Contents
      </p>
      <ul className="space-y-1">
        {SECTIONS.map((s) => (
          <li key={s.id}>
            <button
              onClick={() => onSelect(s.id)}
              className={`w-full text-left text-[12px] px-3 py-1.5 rounded-lg transition-colors ${
                activeId === s.id
                  ? "bg-white/8 text-ink font-medium"
                  : "text-ink-3 hover:text-ink-2 hover:bg-white/4"
              }`}
            >
              {s.title}
            </button>
          </li>
        ))}
      </ul>
    </nav>
  );
}

function SectionBlock({ section }: { section: Section }) {
  return (
    <section
      id={section.id}
      className="scroll-mt-8 pb-10 border-b border-line last:border-0 last:pb-0"
    >
      <h2 className="text-base font-semibold text-ink mb-4">{section.title}</h2>
      <div className="text-[13px] text-ink-2 leading-relaxed space-y-3 [&_ul]:mt-2 [&_ul]:ml-4 [&_ul]:space-y-1.5 [&_ul]:list-disc [&_ul]:list-outside [&_ul]:marker:text-ink-3/60 [&_table]:w-full">
        {section.content}
      </div>
    </section>
  );
}

// ── Main Component ─────────────────────────────────────────────────────────

export default function PrivacyClient() {
  const [activeId, setActiveId] = useState(SECTIONS[0].id);

  function scrollTo(id: string) {
    setActiveId(id);
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
  }

  return (
    <div className="page-document">

      {/* ── Page header ─────────────────────────────────────────────── */}
      <div className="mb-10 pb-8 border-b border-line">
        <div className="flex items-center gap-2 mb-4">
          <Link
            href="/"
            className="text-[11px] text-ink-3/60 hover:text-ink-2 transition-colors"
          >
            VoidCode
          </Link>
          <span className="text-ink-3/60">/</span>
          <span className="text-[11px] text-ink-2">Privacy Policy</span>
        </div>

        <div className="flex items-start justify-between flex-wrap gap-4">
          <div>
            <h1 className="text-2xl font-semibold text-ink mb-2">Privacy Policy</h1>
            <p className="text-sm text-ink-3">
              What this application stores on your machine, what leaves it, and what an optional account keeps.
            </p>
          </div>
          <div className="flex flex-col items-end gap-1">
            <span className="text-[11px] text-ink-3/60">Last updated</span>
            {/* Revised with the rewrite. Section 12 makes this the signal that the Policy changed,
                so it has to move whenever the substance does. */}
            <span className="text-[12px] text-ink-2 font-medium">19 September 2026</span>
          </div>
        </div>

        {/* GDPR / Privacy Act badge row */}
        <div className="mt-6 flex flex-wrap items-center gap-3">
          {[
            { label: "Privacy Act 1988 (Cth)", color: "green" },
            { label: "Australian Privacy Principles", color: "green" },
            { label: "Victorian Privacy Legislation", color: "blue" },
          ].map(({ label, color }) => (
            <span
              key={label}
              className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-medium border ${
                color === "green"
                  ? "border-line-strong bg-void-3 text-ink"
                  : "border-line bg-void-2 text-ink-2"
              }`}
            >
              <span aria-hidden className={`h-1.5 w-1.5 rounded-full ${color === "green" ? "bg-ink" : "border border-ink-3"}`} />
              {label}
            </span>
          ))}
        </div>
      </div>

      {/* ── Body: ToC sidebar + sections ────────────────────────────── */}
      <div className="flex gap-12">
        <TableOfContents activeId={activeId} onSelect={scrollTo} />

        {/* Sections */}
        <div className="flex-1 min-w-0 space-y-10">
          {SECTIONS.map((section) => (
            <SectionBlock key={section.id} section={section} />
          ))}

          {/* Bottom nav */}
          <div className="pt-6 flex items-center justify-between">
            <Link
              href="/terms"
              className="flex items-center gap-2 text-[12px] text-ink-3 hover:text-ink transition-colors group"
            >
              <svg className="w-3.5 h-3.5 group-hover:-translate-x-0.5 transition-transform" viewBox="0 0 14 14" fill="none">
                <path d="M9 2L4 7L9 12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              Terms of Use
            </Link>
            <button
              onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
              className="flex items-center gap-2 text-[12px] text-ink-3 hover:text-ink transition-colors group"
            >
              Back to top
              <svg className="w-3.5 h-3.5 group-hover:-translate-y-0.5 transition-transform" viewBox="0 0 14 14" fill="none">
                <path d="M2 9L7 4L12 9" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
