import { cn } from "@/lib/utils";
import ThinkingBlock from "@/components/VoidCodeAI/ThinkingBlock";
import {
  Container,
  Eyebrow,
  MonoLabel,
  Section,
} from "@/components/marketing/primitives/SectionShell";
import { Reveal } from "@/components/motion/Reveal";

/** The five modes, verbatim from the union in `VoidCodeAIPanel.tsx`. */
const MODES = [
  { mode: "TEACHING", trigger: "asks for the answer", reply: "asks the sub-goal question instead" },
  { mode: "DEBUG", trigger: "tests are failing", reply: "points at the line, not the fix" },
  { mode: "EXPLAIN", trigger: "asks what a term means", reply: "answers straight — no games" },
  { mode: "FOLLOWUP", trigger: "says they give up", reply: "drops difficulty, keeps agency" },
  { mode: "GENERAL", trigger: "anything else", reply: "short, and back to the problem" },
];

function Row({
  index,
  eyebrow,
  title,
  body,
  visual,
}: {
  index: number;
  eyebrow: string;
  title: React.ReactNode;
  body: React.ReactNode;
  visual: React.ReactNode;
}) {
  const flipped = index % 2 === 1;
  return (
    <div className="grid items-center gap-12 lg:grid-cols-[0.75fr_1.25fr] lg:gap-24">
      <Reveal className={cn(flipped && "lg:order-2")}>
        <Eyebrow>{eyebrow}</Eyebrow>
        <h3 className="mt-5 max-w-[18ch] text-[clamp(1.6rem,2.4vw,2.25rem)] font-light leading-[1.15] tracking-tight text-ink">
          {title}
        </h3>
        <div className="mt-6 max-w-[46ch] space-y-4 text-[0.9375rem] leading-relaxed text-ink-2">
          {body}
        </div>
      </Reveal>
      <Reveal delay={0.12} className={cn("min-w-0", flipped && "lg:order-1")}>
        {visual}
      </Reveal>
    </div>
  );
}

function Panel({ children }: { children: React.ReactNode }) {
  return (
    <div className="overflow-hidden rounded-panel border border-line bg-void-2 p-4 shadow-lift lg:p-6">
      {children}
    </div>
  );
}

export function FeatureRows() {
  return (
    <Section>
      <Container className="space-y-28 lg:space-y-40">
        <Row
          index={0}
          eyebrow="Five modes"
          title={<>Responses are routed by intent.</>}
          body={
            <>
              <p>
                Every message is classified before a token is generated. A question
                about terminology returns a direct explanation. A request for the
                solution does not — it routes to teaching, which never hands over
                working code.
              </p>
              <p>
                Signalling that you are stuck routes elsewhere again: the difficulty
                drops, but you still complete the problem yourself.
              </p>
            </>
          }
          visual={
            <Panel>
              <ul className="divide-y divide-line">
                {MODES.map((item) => (
                  <li
                    key={item.mode}
                    className="grid grid-cols-[7.5rem_1fr] items-start gap-3 py-3 sm:grid-cols-[8rem_1fr_1fr] sm:gap-4"
                  >
                    <MonoLabel
                      className={item.mode === "DEBUG" ? "text-red-400" : "text-ink"}
                    >
                      [{item.mode}]
                    </MonoLabel>
                    <span className="text-xs leading-relaxed text-ink-3">{item.trigger}</span>
                    <span className="col-span-2 text-xs leading-relaxed text-ink-2 sm:col-span-1">
                      {item.reply}
                    </span>
                  </li>
                ))}
              </ul>
            </Panel>
          }
        />

        <Row
          index={1}
          eyebrow="Visible reasoning"
          title={<>Reasoning you can inspect.</>}
          body={
            <>
              <p>
                The tutor reasons before it replies, and that reasoning is available
                to you. Expand it to see the actual trace — what it determined you
                were stuck on, and what it deliberately withheld.
              </p>
              <p>
                Up to 8,192 tokens per response, generated by models running on our
                own hardware rather than a third-party API.
              </p>
            </>
          }
          visual={
            <Panel>
              <ThinkingBlock
                defaultOpen
                tokenCount={331}
                content={
                  "Shape test passes, mask test passes, distribution test fails. So the maths is right " +
                  "and the reduction axis is wrong — softmax is on dim=-2 where it should be dim=-1.\n\n" +
                  "Do not name the axis. Give them a one-line experiment that makes the wrong axis " +
                  "visible, because they will hit this exact bug again in multi-head attention and " +
                  "need to recognise it on their own."
                }
              />
            </Panel>
          }
        />

        <Row
          index={2}
          eyebrow="Real execution"
          title={<>Real execution, read in context.</>}
          body={
            <>
              <p>
                A full editor and real test cases, run in a sandbox. When a case
                fails, the tutor already has the result — which case, which line and
                what was returned — before you finish describing it.
              </p>
              <p>That is the difference between a chat window and a workspace.</p>
            </>
          }
          visual={
            <Panel>
              {/*
                Python only, because that is what the catalogue is. All 125
                executable items ship exactly one `code_templates` entry and it is
                Python — `verify_problems.py` fails an item that ships anything
                else, and the workspace's language dropdown derives its options
                from the fetched templates, so it has only ever shown one.
                This panel used to list Python, JavaScript, C++ and Java, and the
                prose beside it promised "four languages". Judge0 is configured for
                all four (`lib/constants.ts`), which is presumably where the claim
                came from — but a runtime the catalogue never uses is not a feature.
              */}
              <div className="flex flex-wrap gap-2">
                {["Python"].map((language) => (
                  <span
                    key={language}
                    className="rounded-full border border-line-strong px-3 py-1 font-mono text-[11px] text-ink-2"
                  >
                    {language}
                  </span>
                ))}
              </div>
              <div className="mt-4 space-y-2 rounded-lg bg-[#040407] p-4 font-mono text-[11px] leading-relaxed">
                <p className="text-ink-3">$ run tests</p>
                <p className="text-green-400">✓ shape (2, 8, 16, 64) → (2, 8, 16, 64)</p>
                <p className="text-green-400">✓ causal mask — no attention above diagonal</p>
                <p className="text-red-400">✗ rows sum to 1 — attn.sum(-1) != ones</p>
                <p className="pt-1 text-ink-3">2 / 3 test cases passed · 0.41s · 68MB</p>
              </div>
            </Panel>
          }
        />
      </Container>
    </Section>
  );
}
